void drive_straight();
void drive_backward();
void bank_right();
void bank_left();
void turn_right();
void turn_left();
void arc10();
void fetch();
void elf();
int seenball();
double ballx;
double bally;
void seeing_ball();
void printball();
void canned();
void suck(int speed);
void shoot(int speed);
